version: '3'
services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    # ローカルのdb入力済みデータをコンテナに同期する(DBは基本コンテナ内だけで動作するため)
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL＿ROOT＿PASSWORD: password
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    # webサービスはdbに依存していることを宣言
    depends_on:
      - db

